name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x # Ensure this matches your project's target framework

      # Install dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Build the solution
      - name: Build Solution
        run: dotnet build --no-restore --configuration Release

      # Run Tests
      - name: Run Tests
        run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test_results.trx"

      # Publish test results
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_results.trx
